In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
'key2' : ['one', 'two', 'one', 'two', 'one'],
'data1' : np.arange(5),
'data2' : np.arange(5,0,-1)})
df

  key1 key2  data1  data2
0    a  one      0      5
1    a  two      1      4
2    b  one      2      3
3    b  two      3      2
4    a  one      4      1

In [ ]:
#single key
grouped = df['data1'].groupby(df['key1'])
print(grouped)

<pandas.core.groupby.generic.SeriesGroupBy object at 0x7f769ff6fb50>

In [ ]:
grouped.mean()

key1
a    1.666667
b    2.500000
Name: data1, dtype: float64

In [ ]:
#multiple keys
means = df['data1'].groupby([df['key1'], df['key2']]).mean()
means

key1  key2
a     one    -0.123964
      two    -0.758399
b     one     0.108340
      two    -0.314953
Name: data1, dtype: float64

In [ ]:
means.unstack()

key2       one       two
key1
a    -0.123964 -0.758399
b     0.108340 -0.314953

In [ ]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

In [ ]:
people = pd.DataFrame(np.random.randn(5, 5),
  columns=['a', 'b', 'c', 'd', 'e'],
  index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])
people.iloc[2:3, [1, 2]] = np.nan # Add a few NA values
people

               a         b         c         d         e
Joe    -0.179613 -1.633822  1.092942 -0.270305 -0.779504
Steve   0.687997  0.991164  0.554747  0.172056 -0.425889
Wes     0.808498       NaN       NaN -0.819936 -0.729674
Jim     0.512248 -1.242796  0.497688  0.295824  0.441626
Travis -0.016216 -0.317920  0.341128 -1.349989 -0.345635

In [ ]:
people.groupby(len).sum()

          a         b         c         d         e
3  1.141134 -2.876618  1.590630 -0.794417 -1.067551
5  0.687997  0.991164  0.554747  0.172056 -0.425889
6 -0.016216 -0.317920  0.341128 -1.349989 -0.345635

In [ ]:
columns = pd.MultiIndex.from_arrays([['US', 'US', 'US', 'JP', 'JP'],
  [1, 3, 5, 1, 3]],
  names=['cty', 'tenor'])
hier_df = pd.DataFrame(np.random.randn(4, 5), columns=columns)
hier_df

cty          US                            JP
tenor         1         3         5         1         3
0     -0.685712  1.197571  0.397936 -0.427073  0.117360
1      0.833758 -0.261208  0.544302 -0.161061  0.874813
2      0.176517 -0.036601  2.717888  1.147261  0.297397
3     -1.537305 -1.702236 -1.723833  0.373292 -0.026879

In [ ]:
hier_df.groupby(level='cty', axis=1).count()

cty  JP  US
0     2   3
1     2   3
2     2   3
3     2   3

# Aggregation Function

In [ ]:
df

  key1 key2  data1  data2
0    a  one      0      5
1    a  two      1      4
2    b  one      2      3
3    b  two      3      2
4    a  one      4      1

In [ ]:
grouped = df.groupby('key1')
grouped['data1'].quantile(0.9)

key1
a    3.4
b    2.9
Name: data1, dtype: float64

In [ ]:
print(grouped['data1'].count())
print(grouped['data1'].sum())
print(grouped['data1'].mean())
print(grouped['data1'].median())
print(grouped['data1'].first())
print(grouped['data1'].last())

key1
a    3
b    2
Name: data1, dtype: int64
key1
a    5
b    5
Name: data1, dtype: int64
key1
a    1.666667
b    2.500000
Name: data1, dtype: float64
key1
a    1.0
b    2.5
Name: data1, dtype: float64
key1
a    0
b    2
Name: data1, dtype: int64
key1
a    4
b    3
Name: data1, dtype: int64

In [ ]:
def peak_to_peak(arr):
  return arr.max() - arr.min()
grouped.agg(peak_to_peak)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Dropping invalid columns in DataFrameGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the aggregating function.
  This is separate from the ipykernel package so we can avoid doing imports until

             SINO  TotalBill  Tips  Size   Tip_Pct
Day  Smoker
Fri  No         3       0.26  0.25   0.0  0.012768
     Yes        8      34.42  3.73   2.0  0.159925
Sat  No        56      37.76  5.48   2.0  0.170882
     Yes       20      34.94  4.00   3.0  0.246806
Sun  No        55      26.49  4.99   2.0  0.193226
Thur No        12      24.76  4.02   3.0  0.109712
     Yes        0       0.00  0.00   0.0  0.000000

In [ ]:
#Column-Wise and Multiple Function Application
tips = pd.read_csv('/content/drive/MyDrive/Advance Python/Working with Data_Pandas/Tips.csv')
tips.head()

   SINO  TotalBill  Tips Smoker  Day    Time  Size
0     1      16.99  1.01     No  Sun  Dinner   2.0
1     2      10.34  1.66     No  Sun  Dinner   3.0
2     3      21.01  3.50     No  Sun  Dinner   3.0
3     4      23.68  3.31     No  Sun  Dinner   2.0
4     5      24.59  3.61     No  Sun  Dinner   4.0

In [ ]:
# Add tip percentage of total bill
tips['Tip_Pct'] = tips['Tips'] / tips['TotalBill']
tips

    SINO  TotalBill  Tips Smoker  Day    Time  Size   Tip_Pct
0      1      16.99  1.01     No  Sun  Dinner   2.0  0.059447
1      2      10.34  1.66     No  Sun  Dinner   3.0  0.160542
2      3      21.01  3.50     No  Sun  Dinner   3.0  0.166587
3      4      23.68  3.31     No  Sun  Dinner   2.0  0.139780
4      5      24.59  3.61     No  Sun  Dinner   4.0  0.146808
..   ...        ...   ...    ...  ...     ...   ...       ...
95    96      40.17  4.73    Yes  Fri  Dinner   4.0  0.117750
96    97      27.28  4.00    Yes  Fri  Dinner   2.0  0.146628
97    98      12.03  1.50    Yes  Fri  Dinner   2.0  0.124688
98    99      21.01  3.00    Yes  Fri  Dinner   2.0  0.142789
99   100      25.10   NaN     No  NaN   Lunch   2.0       NaN

[100 rows x 8 columns]

In [ ]:
grouped = tips.groupby(['Day','Smoker'])

In [ ]:
grouped_pct = grouped['Tip_Pct']

In [ ]:
grouped_pct.agg('mean')

Day   Smoker
Fri   No        0.149241
      Yes       0.153258
Sat   No        0.149257
      Yes       0.170484
Sun   No        0.168910
Thur  No        0.167974
      Yes       0.152999
Name: Tip_Pct, dtype: float64

In [ ]:
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
Day  Smoker
Fri  No      0.149241  0.009028      0.012768
     Yes     0.153258  0.053660      0.159925
Sat  No      0.149257  0.034594      0.170882
     Yes     0.170484  0.062768      0.246806
Sun  No      0.168910  0.044269      0.193226
Thur No      0.167974  0.036923      0.109712
     Yes     0.152999       NaN      0.000000

In [ ]:
grouped_pct.agg([('avg_of_Tip_Per', 'mean'), ('max_of_Tip_Per', np.max)])

             avg_of_Tip_Per  max_of_Tip_Per
Day  Smoker
Fri  No            0.149241        0.155625
     Yes           0.153258        0.263480
Sat  No            0.149257        0.227679
     Yes           0.170484        0.325733
Sun  No            0.168910        0.252672
Thur No            0.167974        0.236746
     Yes           0.152999        0.152999

In [ ]:
#Multiple function on same coulumn
functions = ['count', 'mean', 'max']
result = grouped['Tip_Pct', 'TotalBill'].agg(functions)
result.to_csv("resulr.csv")
print(result)

            Tip_Pct                     TotalBill
              count      mean       max     count       mean    max
Day  Smoker
Fri  No           2  0.149241  0.155625         2  22.620000  22.75
     Yes          7  0.153258  0.263480         7  21.647143  40.17
Sat  No          24  0.149257  0.227679        25  19.062000  48.27
     Yes         11  0.170484  0.325733        11  18.254545  38.01
Sun  No          32  0.168910  0.252672        32  19.455625  35.26
Thur No          11  0.167974  0.236746        11  20.179091  34.83
     Yes          1  0.152999  0.152999         1  32.680000  32.68

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
result['Tip_Pct']

             count      mean       max
Day  Smoker
Fri  No          2  0.149241  0.155625
     Yes         7  0.153258  0.263480
Sat  No         24  0.149257  0.227679
     Yes        11  0.170484  0.325733
Sun  No         32  0.168910  0.252672
Thur No         11  0.167974  0.236746
     Yes         1  0.152999  0.152999

In [ ]:
#suppose you wanted to select the top five tip_pct values by group.
def top(df, n=5, column='Tip_Pct'):
  return df.sort_values(by=column,ascending=False)[0:n]
top(tips,n=10,column='Size')

    SINO  TotalBill  Tips Smoker   Day    Time  Size   Tip_Pct
63    64      18.29  3.76    Yes   Sat  Dinner   4.0  0.205577
13    14      18.43  3.00     No   Sun  Dinner   4.0  0.162778
77    78      27.20  4.00     No  Thur   Lunch   4.0  0.147059
47    48      32.40  6.00     No   Sun  Dinner   4.0  0.185185
33    34        NaN  2.45     No   Sat  Dinner   4.0       NaN
31    32      18.35  2.50     No   Sat  Dinner   4.0  0.136240
85    86      34.83  5.17     No  Thur   Lunch   4.0  0.148435
25    26      17.81  2.34     No   Sat  Dinner   4.0  0.131387
52    53      34.81  5.20     No   Sun  Dinner   4.0  0.149382
23    24      39.42   NaN    NaN   NaN  Dinner   4.0       NaN

In [43]:
tips.groupby('Smoker').apply(top)
# The top function is called on each row group from the
# DataFrame, and then the results are glued together using pandas.concat, labeling the
# pieces with the group names.

           SINO  TotalBill  Tips Smoker   Day    Time  Size   Tip_Pct
Smoker
No     51    52      10.29  2.60     No   Sun  Dinner   2.0  0.252672
       88    89      24.71  5.85     No  Thur   Lunch   2.0  0.236746
       6      7       8.77  2.00     No   Sun  Dinner   2.0  0.228050
       17    18      16.29  3.71     No   Sun  Dinner   3.0  0.227747
       20    21      17.92  4.08     No   Sat  Dinner   2.0  0.227679
Yes    67    68       3.07  1.00    Yes   Sat  Dinner   1.0  0.325733
       93    94      16.32  4.30    Yes   Fri  Dinner   2.0  0.263480
       63    64      18.29  3.76    Yes   Sat  Dinner   4.0  0.205577
       73    74      25.28  5.00    Yes   Sat  Dinner   2.0  0.197785
       62    63      11.02  1.98    Yes   Sat  Dinner   2.0  0.179673

In [46]:
#If you pass a function to apply that takes other arguments or keywords, you can pass these after the function
tips.groupby(['Smoker','Day']).apply(top, n=1, column='TotalBill')

                SINO  TotalBill  Tips Smoker   Day    Time  Size   Tip_Pct
Smoker Day
No     Fri  94    95      22.75  3.25     No   Fri  Dinner   2.0  0.142857
       Sat  59    60      48.27  6.73     No   Sat  Dinner   4.0  0.139424
       Sun  11    12      35.26  5.00     No   Sun  Dinner   4.0  0.141804
       Thur 85    86      34.83  5.17     No  Thur   Lunch   4.0  0.148435
Yes    Fri  95    96      40.17  4.73    Yes   Fri  Dinner   4.0  0.117750
       Sat  56    57      38.01  3.00    Yes   Sat  Dinner   4.0  0.078927
       Thur 83    84      32.68  5.00    Yes  Thur   Lunch   2.0  0.152999