# Series

In [ ]:
import pandas as pd

In [ ]:
obj=pd.Series([5,6,7,9,-2])
print(obj.values)
print(obj.index)
print(obj.value_counts)

In [ ]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
print(obj2)
print(obj2.index)
obj2['d']=6
print(obj2)
print(obj2[['c', 'a', 'd']])

In [ ]:
print(obj2[obj2>3])
obj2=obj2*3
print(obj2)
print('e' in obj2) #in is membership operator, it check for existence, returns boolean

d    54
b    63
c    27
dtype: int64
d    162
b    189
a   -135
c     81
dtype: int64
False

In [ ]:
#Create series from Dictionary
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
print(sdata)
obj3=pd.Series(sdata)
print(obj3)

In [ ]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
print(pd.isnull(obj4))
print(pd.notnull(obj4))
#Series method
print(obj4.notnull())

In [ ]:
print(obj3 + obj4)

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [ ]:
obj4.name = 'population'
obj4.index.name = 'state'
print(obj4)

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

# DataFrame

In [ ]:
data = {'state data': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame=pd.DataFrame(data)
print(frame.head(2))
print(frame.head(-2))  # Not showing last 2
print(frame.tail(2))
print(frame.tail(-2))  # Not showing first 2

  state data  year  pop
0       Ohio  2000  1.5
1       Ohio  2001  1.7
  state data  year  pop
0       Ohio  2000  1.5
1       Ohio  2001  1.7
2       Ohio  2002  3.6
3     Nevada  2001  2.4
  state data  year  pop
4     Nevada  2002  2.9
5     Nevada  2003  3.2
  state data  year  pop
2       Ohio  2002  3.6
3     Nevada  2001  2.4
4     Nevada  2002  2.9
5     Nevada  2003  3.2

In [ ]:
frame2=pd.DataFrame(data, columns=['pop', 'state data', 'year','abc'],index=['one', 'two', 'three', 'four','five', 'six'])
print(frame2.columns)

Index(['pop', 'state data', 'year', 'abc'], dtype='object')

In [ ]:
import numpy as np
frame2['abc'] =16.5
frame2['abc'] = np.arange(6)
frame2['abc'] = [2,3,5,8,9,7]
print(frame2)
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2['abc'] = val
print(frame2)

       pop state data  year  abc
one    1.5       Ohio  2000    2
two    1.7       Ohio  2001    3
three  3.6       Ohio  2002    5
four   2.4     Nevada  2001    8
five   2.9     Nevada  2002    9
six    3.2     Nevada  2003    7
       pop state data  year  abc
one    1.5       Ohio  2000  NaN
two    1.7       Ohio  2001  NaN
three  3.6       Ohio  2002  NaN
four   2.4     Nevada  2001  NaN
five   2.9     Nevada  2002  NaN
six    3.2     Nevada  2003  NaN

In [ ]:
print(frame2['year'])
print(frame2.year)   # after . column name must be valid variable name 'state data' will not work

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64
one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [ ]:
frame2['eastern'] = frame2['state data'] == 'Ohio'
print(frame2)
del frame2['eastern'] 
print(frame2.columns)

       pop state data  year  abc  eastern
one    1.5       Ohio  2000  NaN     True
two    1.7       Ohio  2001  NaN     True
three  3.6       Ohio  2002  NaN     True
four   2.4     Nevada  2001  NaN    False
five   2.9     Nevada  2002  NaN    False
six    3.2     Nevada  2003  NaN    False
Index(['pop', 'state data', 'year', 'abc'], dtype='object')

In [2]:
import pandas as pd
#Nested Dictionary
pop = {'Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
nFrame=pd.DataFrame(pop)
print(nFrame)

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [9]:
print(nFrame.T)

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [10]:
frame3=pd.DataFrame(pop, index=[2001, 2002, 2000])
pdata = {'Ohio': frame3['Ohio'][:2],'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)
frame3.index.name = 'year'; frame3.columns.name = 'state'
print(frame3)
print(frame3.values)

[[2.4 1.7]
 [2.9 3.6]
 [nan 1.5]]

# Essential Functionalities

In [12]:
#Reindexing  (Return new onject after reindexing)
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [13]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [21]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 4, 5])
print(obj3)
obj=obj3.reindex(range(6), method='ffill')
print(obj)

0      blue
4    purple
5    yellow
dtype: object
0      blue
1      blue
2      blue
3      blue
4    purple
5    yellow
dtype: object

In [32]:
import numpy as np
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'], 
                     columns= ['Ohio', 'Texas', 'California'])
print(frame)
frame2 = frame.reindex(['a', 'b'])
print(frame2)
states = ['Texas', 'Utah']
frame2=frame.reindex(columns=states)
print(frame2)

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
   Texas  Utah
a      1   NaN
c      4   NaN
d      7   NaN

In [39]:
#Drop
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj
obj2=obj.drop(['a','c'])
print(obj2)

d    4.5
b    7.2
dtype: float64

In [45]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
#print(data)
#print(data.drop(['Colorado', 'Ohio']))
#print(data.drop('two', axis=1))
#print(data.drop('three', axis="columns"))
data.drop('Colorado',inplace=True)
print(data)

          one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15