In [1]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

In [ ]:
df.sum()

In [ ]:
df.sum(axis='columns')

In [ ]:
df.mean(axis='columns', skipna=False)

In [ ]:
df.idxmax()

In [ ]:
df.cumsum()

In [ ]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [ ]:
uniques = obj.unique()
uniques

In [ ]:
obj.value_counts()

In [ ]:
pd.value_counts(obj.values, sort=False)

In [ ]:
mask = obj.isin(['b', 'c'])
print(mask)
print(obj[mask])

NameError: ignored

In [ ]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

# Read & Write Data

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/sample_data/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [ ]:
lst=['a','b','c','d','messages']
df=pd.read_csv("/content/sample_data/ex2.csv",names=lst,index_col='a') #names column heading  ,index_col=['a','b'] ,names=lst
print(df)

    b   c   d messages
a
1   2   3   4    hello
5   6   7   8    world
9  10  11  12      foo

In [ ]:
# df=pd.read_csv("/content/sample_data/ex1.csv",nrows=2)#skiprows=[2])
# df
df=pd.read_csv("/content/sample_data/ex1.csv",skiprows=range(1,3))#skiprows=[2])
df

   a   b   c   d message
0  9  10  11  12     foo

In [ ]:
df1=pd.read_table("/content/sample_data/ex1.txt",sep=":")
df1

   a  \tb \tc\td\tmessage
0  1    2   \t3\t4\thello
1  5    6   \t7\t8\tworld
2  9   10   \t11\t12\tfoo

In [ ]:
df4=pd.read_csv("/content/sample_data/ex3.csv")
df4

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

In [ ]:
pd.isnull(df4)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

In [ ]:
result = pd.read_csv('/content/sample_data/ex4.csv', na_values=['##','??','foo'])
result

  something    a   b     c   d message
0       one  1.0   2   3.0   4     NaN
1       two  5.0   6   NaN   8   world
2     three  9.0  10  11.0  12     NaN
3      four  NaN  10   NaN  12   Hello
4      five  9.0  10  11.0  12     How

In [ ]:
sentinels = {'message': ['foo', 'NA'], 'something': ['two']}
result = pd.read_csv('/content/sample_data/ex3.csv', na_values=sentinels)
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       NaN  5   6   NaN   8   world
2     three  9  10  11.0  12     NaN

In [ ]:
result.to_csv('/content/sample_data/out.csv')

In [ ]:
import sys
result.to_csv(sys.stdout, sep='\t',na_rep='Unknown')

	something	a	b	c	d	message
0	one	1.0	2	3.0	4	Unknown
1	two	5.0	6	Unknown	8	world
2	three	9.0	10	11.0	12	Unknown
3	four	Unknown	10	Unknown	12	Hello
4	five	9.0	10	11.0	12	How

In [ ]:
`result.to_csv(sys.stdout, index=False, header=False)

one,1.0,2,3.0,4,
two,5.0,6,,8,world
three,9.0,10,11.0,12,
four,,10,,12,Hello
five,9.0,10,11.0,12,How

In [ ]:
result.to_csv(sys.stdout, index=False, columns=['a', 'b', 'c'])

a,b,c
1.0,2,3.0
5.0,6,
9.0,10,11.0
,10,
9.0,10,11.0

# Interacting with API

In [ ]:
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)
#print(resp)
data = resp.json()
data
# print(data[3]['title'])

#print(data[2]['title'])

[{'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',
  'body': "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\ndf = pd.DataFrame(\r\n    index=pd.MultiIndex.from_arrays([[], []], names=['a', 'b']),\r\n    columns=['A', 'B']\r\n)\r\ndf.to_excel('test.xlsx')\n```\n\n\n### Issue Description\n\n```\r\n---------------------------------------------------------------------------\r\nIndexError                                Traceback (most recent call last)\r\nInput In [9], in <cell line: 7>()\r\n      1 import pandas as pd\r\n      3 df = pd.DataFrame(\r\n      4     index=pd.MultiIndex.from_arrays([[], []], names=['a', 'b']),\r\n      5     columns=['A', 'B']\r\n      6 )\r\n----> 7 df.to_excel('test.xlsx')\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\core\\generic.py:2345, in NDFrame.to_excel(self, excel_writer, sheet_name, na_rep, float_format, columns, header, index, index_label, startrow, startcol, engine, merge_cells, encoding, inf_rep, verbose, freeze_panes, storage_options)\r\n   2332 from pandas.io.formats.excel import ExcelFormatter\r\n   2334 formatter = ExcelFormatter(\r\n   2335     df,\r\n   2336     na_rep=na_rep,\r\n   (...)\r\n   2343     inf_rep=inf_rep,\r\n   2344 )\r\n-> 2345 formatter.write(\r\n   2346     excel_writer,\r\n   2347     sheet_name=sheet_name,\r\n   2348     startrow=startrow,\r\n   2349     startcol=startcol,\r\n   2350     freeze_panes=freeze_panes,\r\n   2351     engine=engine,\r\n   2352     storage_options=storage_options,\r\n   2353 )\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\io\\formats\\excel.py:894, in ExcelFormatter.write(self, writer, sheet_name, startrow, startcol, freeze_panes, engine, storage_options)\r\n    891     need_save = True\r\n    893 try:\r\n--> 894     writer.write_cells(\r\n    895         formatted_cells,\r\n    896         sheet_name,\r\n    897         startrow=startrow,\r\n    898         startcol=startcol,\r\n    899         freeze_panes=freeze_panes,\r\n    900     )\r\n    901 finally:\r\n    902     # make sure to close opened file handles\r\n    903     if need_save:\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\io\\excel\\_xlsxwriter.py:227, in XlsxWriter.write_cells(self, cells, sheet_name, startrow, startcol, freeze_panes)\r\n    224 if validate_freeze_panes(freeze_panes):\r\n    225     wks.freeze_panes(*(freeze_panes))\r\n--> 227 for cell in cells:\r\n    228     val, fmt = self._value_with_fmt(cell.val)\r\n    230     stylekey = json.dumps(cell.style)\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\io\\formats\\excel.py:831, in ExcelFormatter.get_formatted_cells(self)\r\n    830 def get_formatted_cells(self) -> Iterable[ExcelCell]:\r\n--> 831     for cell in itertools.chain(self._format_header(), self._format_body()):\r\n    832         cell.val = self._format_value(cell.val)\r\n    833         yield cell\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\io\\formats\\excel.py:630, in ExcelFormatter._format_header_regular(self)\r\n    628     coloffset = 1\r\n    629     if isinstance(self.df.index, MultiIndex):\r\n--> 630         coloffset = len(self.df.index[0])\r\n    632 colnames = self.columns\r\n    633 if self._has_aliases:\r\n\r\nFile E:\\Program Files\\Python39\\lib\\site-packages\\pandas\\core\\indexes\\multi.py:2075, in MultiIndex.__getitem__(self, key)\r\n   2073 retval = []\r\n   2074 for lev, level_codes in zip(self.levels, self.codes):\r\n-> 2075     if level_codes[key] == -1:\r\n   2076         retval.append(np.nan)\r\n   2077     else:\r\n\r\nIndexError: index 0 is out of bounds for axis 0 with size 0\r\n```\n\n### Expected Behavior\n\nWrite a sheet with only column header\n\n### Installed Versions\n\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 4bfe3d07b4858144c219b9346329027024102ab6\r\npython           : 3.9.7.final.0\r\npython-bits      : 64\r\nOS               : Windows\r\nOS-release       : 10\r\nVersion          : 10.0.19042\r\nmachine          : AMD64\r\nprocessor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : None\r\nLOCALE           : Chinese (Simplified)_China.936\r\n\r\npandas           : 1.4.2\r\nnumpy            : 1.22.3\r\npytz             : 2022.1\r\ndateutil         : 2.8.2\r\npip              : 22.0.4\r\nsetuptools       : 57.4.0\r\nCython           : 0.29.28\r\npytest           : 7.1.1\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : 3.0.3\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : 1.0.2\r\npsycopg2         : None\r\njinja2           : 3.0.3\r\nIPython          : 8.2.0\r\npandas_datareader: None\r\nbs4              : 4.10.0\r\nbottleneck       : None\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmarkupsafe       : 2.0.1\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : 0.8.9\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n\r\n</details>\r\n",
  'closed_at': None,
  'comments': 0,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/comments',
  'created_at': '2022-04-26T02:47:56Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46873',
  'id': 1215290588,
  'labels': [{'color': 'e10c02',
    'default': False,
    'description': None,
    'id': 76811,
    'name': 'Bug',
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},
   {'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member',
    'id': 1954720290,
    'name': 'Needs Triage',
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'I_kwDOAA0YD85Ib9zc',
  'number': 46873,
  'performed_via_github_app': None,
  'reactions': {'+1': 0,
   '-1': 0,
   'confused': 0,
   'eyes': 0,
   'heart': 0,
   'hooray': 0,
   'laugh': 0,
   'rocket': 0,
   'total_count': 0,
   'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/reactions'},
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/timeline',
  'title': 'BUG: Error when exporting an empty DataFrame with MultiIndex to xlsx file',
  'updated_at': '2022-04-26T02:47:56Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/7558201?v=4',
   'events_url': 'https://api.github.com/users/WEGFan/events{/privacy}',
   'followers_url': 'https://api.github.com/users/WEGFan/followers',
   'following_url': 'https://api.github.com/users/WEGFan/following{/other_user}',
   'gists_url': 'https://api.github.com/users/WEGFan/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/WEGFan',
   'id': 7558201,
   'login': 'WEGFan',
   'node_id': 'MDQ6VXNlcjc1NTgyMDE=',
   'organizations_url': 'https://api.github.com/users/WEGFan/orgs',
   'received_events_url': 'https://api.github.com/users/WEGFan/received_events',
   'repos_url': 'https://api.github.com/users/WEGFan/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/WEGFan/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/WEGFan/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/WEGFan'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',
  'body': "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [ ] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nimport pandas as pd\r\n\r\ndf = pd.DataFrame({\r\n    'a': [1, 2, 3],\r\n    'b': pd.Series([True, False, True], dtype=pd.BooleanDtype()),\r\n})\r\nprint(df.select_dtypes(include='number').columns)\r\n# Output: Index(['a', 'b'], dtype='object')\n```\n\n\n### Issue Description\n\nThe `DataFrame.select_dtypes` method includes columns with `dtype` of `BooleanDtype` when `include='number'` is given as a kwarg. This is different than the behavior for columns with `dtype` of `bool` and seems like a bug.\n\n### Expected Behavior\n\nThe code above should output: `Index(['a'], dtype='object')`\r\n\n\n### Installed Versions\n\n<details>\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 4bfe3d07b4858144c219b9346329027024102ab6\r\npython           : 3.9.12.final.0\r\npython-bits      : 64\r\nOS               : Darwin\r\nOS-release       : 20.6.0\r\nVersion          : Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64\r\nmachine          : x86_64\r\nprocessor        : i386\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : en_US.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.4.2\r\nnumpy            : 1.21.5\r\npytz             : 2021.3\r\ndateutil         : 2.8.2\r\npip              : 21.2.4\r\nsetuptools       : 59.8.0\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : None\r\nIPython          : 8.2.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : 1.3.4\r\nbrotli           : None\r\nfastparquet      : None\r\nfsspec           : None\r\ngcsfs            : None\r\nmarkupsafe       : None\r\nmatplotlib       : None\r\nnumba            : None\r\nnumexpr          : 2.8.1\r\nodfpy            : None\r\nopenpyxl         : None\r\npandas_gbq       : None\r\npyarrow          : None\r\npyreadstat       : None\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : None\r\nsnappy           : None\r\nsqlalchemy       : None\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nzstandard        : None\r\n\r\n</details>\r\n",
  'closed_at': None,
  'comments': 0,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/comments',
  'created_at': '2022-04-25T19:37:48Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46870',
  'id': 1214958040,
  'labels': [{'color': 'e10c02',
    'default': False,
    'description': None,
    'id': 76811,
    'name': 'Bug',
    'node_id': 'MDU6TGFiZWw3NjgxMQ==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug'},
   {'color': '0052cc',
    'default': False,
    'description': 'Issue that has not been reviewed by a pandas team member',
    'id': 1954720290,
    'name': 'Needs Triage',
    'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'I_kwDOAA0YD85IasnY',
  'number': 46870,
  'performed_via_github_app': None,
  'reactions': {'+1': 0,
   '-1': 0,
   'confused': 0,
   'eyes': 0,
   'heart': 0,
   'hooray': 0,
   'laugh': 0,
   'rocket': 0,
   'total_count': 0,
   'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/reactions'},
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/timeline',
  'title': "BUG: DataFrame.select_dtypes(include='number') includes BooleanDtype columns",
  'updated_at': '2022-04-25T19:37:48Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/3409997?v=4',
   'events_url': 'https://api.github.com/users/macks22/events{/privacy}',
   'followers_url': 'https://api.github.com/users/macks22/followers',
   'following_url': 'https://api.github.com/users/macks22/following{/other_user}',
   'gists_url': 'https://api.github.com/users/macks22/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/macks22',
   'id': 3409997,
   'login': 'macks22',
   'node_id': 'MDQ6VXNlcjM0MDk5OTc=',
   'organizations_url': 'https://api.github.com/users/macks22/orgs',
   'received_events_url': 'https://api.github.com/users/macks22/received_events',
   'repos_url': 'https://api.github.com/users/macks22/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/macks22/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/macks22/subscriptions',
   'type': 'User',
   'url': 'https://api.github.com/users/macks22'}},
 {'active_lock_reason': None,
  'assignee': None,
  'assignees': [],
  'author_association': 'NONE',
  'body': "### Pandas version checks\n\n- [X] I have checked that this issue has not already been reported.\n\n- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\n\n- [X] I have confirmed this bug exists on the main branch of pandas.\n\n\n### Reproducible Example\n\n```python\nA value is trying to be set on a copy of a slice from a DataFrame.\r\nTry using .loc[row_indexer,col_indexer] = value instead\r\n\r\nSee the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\r\n  available_data['loading'] = 1\n```\n\n\n### Issue Description\n\nSorry but for the life of me i cant create a reproducible example. It is just a dataframe that was created using `maindf.query('some_time > @todays_datetime')`\r\navailable_data.values.base is maindf.values.base # False\n\n### Expected Behavior\n\nnot have the warning\n\n### Installed Versions\n\n<details>\r\n\r\n\r\nINSTALLED VERSIONS\r\n------------------\r\ncommit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b\r\npython           : 3.8.5.final.0\r\npython-bits      : 64\r\nOS               : Linux\r\nOS-release       : 5.4.0-1051-azure\r\nVersion          : #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021\r\nmachine          : x86_64\r\nprocessor        : x86_64\r\nbyteorder        : little\r\nLC_ALL           : None\r\nLANG             : C.UTF-8\r\nLOCALE           : en_US.UTF-8\r\n\r\npandas           : 1.3.2\r\nnumpy            : 1.21.2\r\npytz             : 2021.1\r\ndateutil         : 2.8.2\r\npip              : 21.2.2\r\nsetuptools       : 52.0.0.post20210125\r\nCython           : None\r\npytest           : None\r\nhypothesis       : None\r\nsphinx           : None\r\nblosc            : None\r\nfeather          : None\r\nxlsxwriter       : None\r\nlxml.etree       : None\r\nhtml5lib         : None\r\npymysql          : None\r\npsycopg2         : None\r\njinja2           : 3.0.1\r\nIPython          : 7.27.0\r\npandas_datareader: None\r\nbs4              : None\r\nbottleneck       : None\r\nfsspec           : None\r\nfastparquet      : None\r\ngcsfs            : None\r\nmatplotlib       : 3.4.3\r\nnumexpr          : None\r\nodfpy            : None\r\nopenpyxl         : 3.0.9\r\npandas_gbq       : None\r\npyarrow          : 3.0.0\r\npyxlsb           : None\r\ns3fs             : None\r\nscipy            : 1.7.1\r\nsqlalchemy       : 1.4.35\r\ntables           : None\r\ntabulate         : None\r\nxarray           : None\r\nxlrd             : None\r\nxlwt             : None\r\nnumba            : None\r\n\r\n</details>\r\n",
  'closed_at': None,
  'comments': 1,
  'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/comments',
  'created_at': '2022-04-25T19:09:44Z',
  'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/events',
  'html_url': 'https://github.com/pandas-dev/pandas/issues/46869',
  'id': 1214926495,
  'labels': [{'color': '0052cc',
    'default': False,
    'description': None,
    'id': 34444536,
    'name': 'Usage Question',
    'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question'},
   {'color': 'f2f074',
    'default': False,
    'description': 'Warnings that appear or should be added to pandas',
    'id': 1628184320,
    'name': 'Warnings',
    'node_id': 'MDU6TGFiZWwxNjI4MTg0MzIw',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Warnings'},
   {'color': 'be21f2',
    'default': False,
    'description': 'May be closeable, needs more eyeballs',
    'id': 2365504893,
    'name': 'Closing Candidate',
    'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz',
    'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate'}],
  'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/labels{/name}',
  'locked': False,
  'milestone': None,
  'node_id': 'I_kwDOAA0YD85Iak6f',
  'number': 46869,
  'performed_via_github_app': None,
  'reactions': {'+1': 0,
   '-1': 0,
   'confused': 0,
   'eyes': 0,
   'heart': 0,
   'hooray': 0,
   'laugh': 0,
   'rocket': 0,
   'total_count': 0,
   'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/reactions'},
  'repository_url': 'https://api.github.com/repos/pandas-dev/pandas',
  'state': 'open',
  'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/timeline',
  'title': 'BUG: SettingWithCopyWarning',
  'updated_at': '2022-04-25T20:39:00Z',
  'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869',
  'user': {'avatar_url': 'https://avatars.githubusercontent.com/u/53195438?v=4',
   'events_url': 'https://api.github.com/users/iliya-malecki/events{/privacy}',
   'followers_url': 'https://api.github.com/users/iliya-malecki/followers',
   'following_url': 'https://api.github.com/users/iliya-malecki/following{/other_user}',
   'gists_url': 'https://api.github.com/users/iliya-malecki/gists{/gist_id}',
   'gravatar_id': '',
   'html_url': 'https://github.com/iliya-malecki',
   'id': 53195438,
   'login': 'iliya-malecki',
   'node_id': 'MDQ6VXNlcjUzMTk1NDM4',
   'organizations_url': 'https://api.github.com/users/iliya-malecki/orgs',
   'received_events_url': 'https://api.github.com/users/iliya-malecki/received_events',
   'repos_url': 'https://api.github.com/users/iliya-malecki/repos',
   'site_admin': False,
   'starred_url': 'https://api.github.com/users/iliya-malecki/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/iliya-malecki/subscriptions',
   'type': 'User',

In [ ]:
issues = pd.DataFrame(data, columns=['number', 'title','labels', 'state'])
print(issues.head())
issues.to_csv("/content/sample_data/pandas_issues.csv")

NameError: ignored

# Interacting with Database

In [ ]:
import sqlite3
query = "CREATE TABLE test (a VARCHAR(20), b VARCHAR(20),c REAL, d INTEGER);"
con = sqlite3.connect('mydata.sqlite')
con.execute(query)
con.commit()

In [ ]:
data = [('Atlanta', 'Georgia', 1.25, 6),
        ('Tallahassee', 'Florida', 2.6, 3),
        ('Sacramento', 'California', 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)
con.commit()

In [ ]:
cursor = con.execute('select * from test')
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [ ]:
df1=pd.DataFrame(rows, columns=[x[0] for x in cursor.description])
df1

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

In [ ]:
"""The SQLAlchemy project is a popular Python SQL toolkit that abstracts
away many of the common differences between SQL databases"""
import sqlalchemy as sqla
db = sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5

# Missing Values

In [ ]:
import numpy as np
import pandas as pd
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [ ]:
string_data[0] = None
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [ ]:
from numpy import nan as NA
data = pd.Series([1, NA, 3.5, NA, 7])
data.dropna(inplace=True)
data
# similar to data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [ ]:
import pandas as pd
data = pd.DataFrame([[1., 6.5, 3.],[1., NA, NA],[NA, NA, NA], [NA, 6.5, 3.]])
print(data)
#cleaned = data.dropna(axis=1)
cleaned = data.dropna(how='any',axis=0)
cleaned

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

     0    1    2
0  1.0  6.5  3.0

In [ ]:
import numpy as np
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
print(df)
print(df.dropna(axis=0,thresh=4)) # thresh=N requires that a column has at least N non-NaNs to survive.

          0         1         2
0 -1.070413       NaN       NaN
1 -2.216409       NaN       NaN
2 -2.055891       NaN -1.420072
3  1.565736       NaN -0.042791
4  0.857626  0.632143  2.407930
5  1.178308  0.830293  0.730236
6 -1.116332  0.625629 -1.332846
Empty DataFrame
Columns: [0, 1, 2]
Index: []

In [ ]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
print(df)
df.fillna(0,inplace=True)
df

          0         1         2
0  1.064551       NaN       NaN
1  0.297796       NaN       NaN
2 -0.904339       NaN  0.852221
3 -0.516948       NaN  0.133778
4  0.031049  0.495277  0.777311
5 -0.473424 -0.911007  0.184984
6  0.742835  0.118618 -0.979854

          0         1         2
0  1.064551  0.000000  0.000000
1  0.297796  0.000000  0.000000
2 -0.904339  0.000000  0.852221
3 -0.516948  0.000000  0.133778
4  0.031049  0.495277  0.777311
5 -0.473424 -0.911007  0.184984
6  0.742835  0.118618 -0.979854

In [ ]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = NA
df.iloc[:2, 2] = NA
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -1.092747  0.500000  0.000000
1 -1.096953  0.500000  0.000000
2  0.633094  0.500000  0.880200
3 -0.280749  0.500000 -0.807530
4  1.394240 -0.530236 -1.051925
5  0.782387 -0.379564  0.193095
6  1.321929  2.159115 -0.519423

In [ ]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[:2, 1] = NA
df.iloc[:4, 2] = NA
print(df)
df.fillna(method='bfill')
# df.fillna(method='bfill', limit=2)

          0         1         2
0 -0.427160       NaN       NaN
1  0.892236       NaN       NaN
2 -0.906353  0.495243       NaN
3  1.957676  0.499477       NaN
4 -1.044126  1.634750  0.003486
5  0.743390 -0.707861  1.735465

          0         1         2
0 -0.427160  0.495243  0.003486
1  0.892236  0.495243  0.003486
2 -0.906353  0.495243  0.003486
3  1.957676  0.499477  0.003486
4 -1.044126  1.634750  0.003486
5  0.743390 -0.707861  1.735465

In [ ]:
data.fillna(data.mean())

     0    1    2
0  1.0  6.5  3.0
1  1.0  6.5  3.0
2  1.0  6.5  3.0
3  1.0  6.5  3.0

# Data Tranformation

## *Duplicate Values*

In [ ]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],'k2': [1, 1, 2, 3, 3, 4, 4]})
print(data)
data.duplicated()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [ ]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [ ]:
data = pd.DataFrame({'k1': ['one', 'two','three'] * 2 + ['three'],
                     'k2': [1, 2, 3, 4, 5, 4, 3]})
data['v1'] = range(7)
data

      k1  k2  v1
0    one   1   0
1    two   2   1
2  three   3   2
3    one   4   3
4    two   5   4
5  three   4   5
6  three   3   6

In [ ]:
data.drop_duplicates(['v1'])

      k1  k2  v1
0    one   1   0
1    two   2   1
2  three   3   2
3    one   4   3
4    two   5   4
5  three   4   5
6  three   3   6

In [ ]:
data.drop_duplicates(['k1', 'k2'])
data.drop_duplicates(['k1', 'k2'], keep='last')

      k1  k2  v1
0    one   1   0
1    two   2   1
3    one   4   3
4    two   5   4
5  three   4   5
6  three   3   6

## **Transforming Data Using a Function or Mapping**

In [ ]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon',
  'Pastrami', 'corned beef', 'Bacon',
  'pastrami', 'honey ham', 'nova lox'],
  'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
lowercased = data['food'].str.lower()

In [ ]:
meat_to_animal = {
'bacon': 'pig',
'pulled pork': 'pig',
'pastrami': 'cow',
'corned beef': 'cow',
'honey ham': 'pig',
'nova lox': 'salmon'
}

In [ ]:
data['animal'] = lowercased.map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [ ]:
data['food'].map(lambda x: meat_to_animal[x.lower()]) #lambda function

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [ ]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace(-999, np.nan)
data.replace([-999, -1000], np.nan)
data.replace([-999, -1000], [np.nan, 0])
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [ ]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
  index=['Ohio', 'colorado', 'New york'],
  columns=['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
colorado    4    5      6     7
New york    8    9     10    11

In [ ]:
data.rename(index=str.title, columns=str.upper,inplace=True)
data

          ONE  TWO  THREE  FOUR
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [ ]:
data.rename(index={'Ohio': 'INDIANA'}, columns={'THREE': 'peekaboo'},inplace=True)
data

          ONE  TWO  peekaboo  FOUR
INDIANA     0    1         2     3
Colorado    4    5         6     7
New York    8    9        10    11

In [ ]:
data = pd.DataFrame(np.random.randn(1000, 4))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.014051    -0.007833     0.016793    -0.082053
std       0.994630     1.000900     1.011884     0.988962
min      -3.159084    -2.901373    -3.550263    -3.622493
25%      -0.692644    -0.701994    -0.697452    -0.791819
50%       0.016975    -0.021223     0.014359     0.025727
75%       0.675579     0.674956     0.703171     0.622687
max       3.088897     4.262416     3.079164     2.506732

In [ ]:
col = data[2]
print(col)
col[np.abs(col) > 3]

0      0.059408
1     -1.762388
2      1.020509
3     -0.726066
4      0.763751
         ...
995   -0.961968
996   -0.223641
997   -0.372273
998    0.443571
999   -0.863197
Name: 2, Length: 1000, dtype: float64

356   -3.065394
606    3.079164
991   -3.550263
Name: 2, dtype: float64

In [ ]:
data[(np.abs(data) > 3).any(1)]

            0         1         2         3
134  3.054610 -0.026282 -1.901980 -0.128311
194  0.234151  0.239104  1.404313 -3.149106
345  0.006849  0.285085  3.177876  1.131062
564  0.202410  3.224047 -0.773499 -0.394639
792 -0.463515 -0.593516  0.611160  3.240441
859  0.142886  0.734939  3.397545 -1.851439
869 -0.560696  3.097805  0.626809 -1.563986
870 -0.835653  0.895916 -0.180579 -3.260671
925 -2.241110 -0.086599 -1.751250 -3.791933

In [ ]:
data[np.abs(data) > 3] = np.sign(data) * 3
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.015310     0.021045     0.021738    -0.007239
std       0.988179     0.998655     1.012693     1.036305
min      -2.896168    -2.841123    -2.721848    -3.000000
25%      -0.688337    -0.673803    -0.633762    -0.676693
50%      -0.018270     0.054878    -0.004744    -0.039308
75%       0.670327     0.687879     0.751269     0.708620
max       3.000000     3.000000     3.000000     3.000000

# String Manipulation

In [9]:
val = 'a,b, guido '
val.split(',')

['a', 'b', ' guido ']

In [28]:
name = ' Ditya  '
name.strip()

'Ditya'

In [36]:
n = 'Yukti, Vrunal, Madalsa'
n.lower()
n.replace("Vrunal", "Ditya")
n.count('u')

2

In [3]:
#pieces = [x.strip() for x in val.split(',')]
pieces=[]
val1=val.split(',')
for x in val1:
  pieces.append(x.strip())
print(pieces)

['a', 'b', 'guido']

In [4]:
first, second, third = pieces
print(first + '::' + second + '::' + third)

a::b::guido

In [32]:
n1 = "Yukti "
n2 = "Madalsa "
n3 = "Bhavna"
n1 + n2 + n3

'Yukti Madalsa Bhavna'

In [7]:
' cut '.join(pieces)

'a cut b cut guido'

In [ ]:
'guido' in val

True

In [ ]:
val.index(',')

1

In [ ]:
val.find(':')

-1

In [ ]:
val.index(':')

ValueError: ignored

In [15]:
val.count(',')

2

In [ ]:
val.replace(',', '::')

'a::b:: guido'

In [ ]:
val.replace(',', '')

'ab guido'

### Regex

In [ ]:
import re
text = "foo bar\t baz \tqux"
print(text)
re.split('\s+', text)

foo bar	 baz 	qux

['foo', 'bar', 'baz', 'qux']

In [ ]:
#a reusable regex object
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [ ]:
regex.findall(text)

[' ', '\t ', ' \t']

In [ ]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com
"""
pattern = r'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [ ]:
m = regex.search(text)
m

In [ ]:
print(regex.match(text))

None

In [ ]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

### String function with pandas vector

In [ ]:
data = {'Dave': 'dave@google.com', 'Steve': 'steve@gmail.com',
  'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [ ]:
data.isnull()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [ ]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [ ]:
pattern

'[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,4}'

In [ ]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [dave@google.com]
Steve    [steve@gmail.com]
Rob        [rob@gmail.com]
Wes                    NaN
dtype: object

In [ ]:
matches = data.str.match(pattern, flags=re.IGNORECASE)
matches

Dave     True
Steve    True
Rob      True
Wes       NaN
dtype: object

In [ ]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

# Data Wrangling

## Hierarchical Indexing

In [ ]:
data = pd.Series(np.random.randn(9),
  index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
  [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    1.411290
   2   -0.699172
   3    0.176786
b  1   -0.731649
   3    0.223901
c  1    0.802515
   2   -0.020080
d  2   -0.264244
   3    0.263117
dtype: float64

In [ ]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [ ]:
data['b']

1   -0.731649
3    0.223901
dtype: float64

In [ ]:
data['b':'c']
data.loc[['b', 'd']]

b  1   -0.731649
   3    0.223901
d  2   -0.264244
   3    0.263117
dtype: float64

In [ ]:
#election is even possible from an “inner” level:
data.loc[:, 2]

a   -0.699172
c   -0.020080
d   -0.264244
dtype: float64

In [ ]:
data.unstack()

          1         2         3
a  1.411290 -0.699172  0.176786
b -0.731649       NaN  0.223901
c  0.802515 -0.020080       NaN
d       NaN -0.264244  0.263117

In [ ]:
data.unstack().stack()

a  1    1.411290
   2   -0.699172
   3    0.176786
b  1   -0.731649
   3    0.223901
c  1    0.802515
   2   -0.020080
d  2   -0.264244
   3    0.263117
dtype: float64

In [ ]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
columns=[['Ohio', 'Ohio', 'Colorado'],
['Green', 'Red', 'Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [ ]:
# The hierarchical levels can have names

frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [ ]:
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [ ]:
#reorder
frame.swaplevel('key1', 'key2')

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
print(frame)
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [ ]:
print(frame)
frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

In [ ]:
print(frame)
frame.sum(level='key1')

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().

state  Ohio     Colorado
color Green Red    Green
key1
a         3   5        7
b        15  17       19

In [ ]:
print(frame)
frame.sum(level='state', axis=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: FutureWarning: Using the level keyword in DataFrame and Series aggregations is deprecated and will be removed in a future version. Use groupby instead. df.sum(level=1) should use df.groupby(level=1).sum().

state      Ohio  Colorado
key1 key2
a    1        1         2
     2        7         5
b    1       13         8
     2       19        11

In [ ]:
frame = pd.DataFrame({'a': range(7), 'b': range(7, 0, -1),
                      'c': ['one', 'one', 'one', 'two', 'two','two', 'two'],
                      'd': [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
frame2 = frame.set_index(['c', 'd'])
print(frame2)

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3
   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

In [ ]:
frame.set_index(['c', 'd'], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

## Combining & Merging

In [ ]:
#Merging
df1 = pd.DataFrame({'abc': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df2 = pd.DataFrame({'abc': ['a', 'b', 'd'],'data2': range(3)})
print(df1)
print(df2)

  abc  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6
  abc  data2
0   a      0
1   b      1
2   d      2

In [ ]:
"""This is an example of a many-to-one join; the data in df1 has multiple rows labeled a
and b, whereas df2 has only one row for each value in the key column"""
print(pd.merge(df1, df2,how="right"))

  key  data1  data2
0   a    2.0      0
1   a    4.0      0
2   a    5.0      0
3   b    0.0      1
4   b    1.0      1
5   b    6.0      1
6   d    NaN      2

In [ ]:
pd.merge(df1, df2, on='abc')

  abc  data1  data2
0   b      0      1
1   b      1      1
2   b      6      1
3   a      2      0
4   a      4      0
5   a      5      0

In [ ]:
"""If the column names are different in each object, you can specify them separately"""
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],'data1': range(7)})
df4 = pd.DataFrame({'lkey': ['a', 'b', 'd'],'data2': range(3)})
print(pd.merge(df3, df4, left_on='lkey', right_on='rkey'))

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    b      6    b      1
3    a      2    a      0
4    a      4    a      0
5    a      5    a      0

In [ ]:
pd.merge(df1, df2, how='outer')

  key  data1  data2
0   b    0.0    1.0
1   b    1.0    1.0
2   b    6.0    1.0
3   a    2.0    0.0
4   a    4.0    0.0
5   a    5.0    0.0
6   c    3.0    NaN
7   d    NaN    2.0

In [ ]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                      'key2': ['one', 'two', 'one'],
                      'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})
print(left)
print(right)
pd.merge(left, right, on=['key1', 'key2'], how='outer')

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3
  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

  key1 key2  lval  rval
0  foo  one   1.0   4.0
1  foo  one   1.0   5.0
2  foo  two   2.0   NaN
3  bar  one   3.0   6.0
4  bar  two   NaN   7.0

In [ ]:
pd.merge(left, right, on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [ ]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

In [ ]:
#Merging on index
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'], 'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])
print(left1)
print(right1)

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5
   group_val
a        3.5
b        7.0

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True)

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0

In [ ]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [ ]:
#Concatenation
arr = np.arange(12).reshape((3, 4))
print(arr)
#np.concatenate([arr, arr], axis=1)
np.concatenate([arr, arr], axis=0)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [ ]:
pd.concat([s1, s2, s3], axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [ ]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: int64

In [ ]:
pd.concat([s1, s4], axis=1)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [ ]:
pd.concat([s1, s4], axis=1, join='inner')

   0  1
a  0  0
b  1  1

In [ ]:
result = pd.concat([s1, s2, s3], keys=['one', 'two', 'three'])
result
result.unstack()

         a    b    c    d    e    f    g
one    0.0  1.0  NaN  NaN  NaN  NaN  NaN
two    NaN  NaN  2.0  3.0  4.0  NaN  NaN
three  NaN  NaN  NaN  NaN  NaN  5.0  6.0

In [ ]:
pd.concat([s1, s2, s3], axis=1, keys=['one', 'two', 'three'])

   one  two  three
a  0.0  NaN    NaN
b  1.0  NaN    NaN
c  NaN  2.0    NaN
d  NaN  3.0    NaN
e  NaN  4.0    NaN
f  NaN  NaN    5.0
g  NaN  NaN    6.0

In [ ]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],columns=['one', 'two'])
print(df1)
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],columns=['three', 'four'])
print(df2)

   one  two
a    0    1
b    2    3
c    4    5
   three  four
a      5     6
c      7     8

In [ ]:
pd.concat([df1, df2], axis=1, keys=['level1', 'level2'])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [ ]:
pd.concat({'level1': df1, 'level2': df2}, axis=1)

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [ ]:
#Overlapping
a = pd.Series([np.nan, 2.5, np.nan, 3.5, 4.5, np.nan],
  index=['f', 'e', 'd', 'c', 'b', 'a'])
a

f    NaN
e    2.5
d    NaN
c    3.5
b    4.5
a    NaN
dtype: float64

In [ ]:
b = pd.Series(np.arange(len(a), dtype=np.float64),
  index=['f', 'e', 'd', 'c', 'b', 'a'])
b[-1]=np.nan
b

f    0.0
e    1.0
d    2.0
c    3.0
b    4.0
a    NaN
dtype: float64

In [ ]:
np.where(pd.isnull(a), b, a)

array([0. , 2.5, 2. , 3.5, 4.5, nan])

In [ ]:
b[:-2].combine_first(a[2:])

a    NaN
b    4.5
c    3.0
d    2.0
e    1.0
f    0.0
dtype: float64

In [ ]:
df1 = pd.DataFrame({'a': [1., np.nan, 5., np.nan],
  'b': [np.nan, 2., np.nan, 6.],
  'c': range(2, 18, 4)})
df2 = pd.DataFrame({'a': [5., 4., np.nan, 3., 7.],
  'b': [np.nan, 3., 4., 6., 8.]})
print(df1)
print(df2)

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14
     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [ ]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

## Reshaping and Pivoting

In [ ]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
  index=pd.Index(['Ohio', 'Colorado'], name='state'),
  columns=pd.Index(['one', 'two', 'three'],
  name='number'))
print(data)
result = data.stack()
result

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

In [ ]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [ ]:
result.unstack(0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [ ]:
result.unstack('state')

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [ ]:
s1 = pd.Series([0, 1, 2, 3], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 5, 6], index=['c', 'd', 'e'])
data2 = pd.concat([s1, s2], keys=['one', 'two'])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: int64

In [ ]:
data2.unstack()

       a    b    c    d    e
one  0.0  1.0  2.0  3.0  NaN
two  NaN  NaN  4.0  5.0  6.0

In [ ]:
data2.unstack().stack()

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
two  c    4.0
     d    5.0
     e    6.0
dtype: float64

In [ ]:
data2.unstack().stack(dropna=False)

one  a    0.0
     b    1.0
     c    2.0
     d    3.0
     e    NaN
two  a    NaN
     b    NaN
     c    4.0
     d    5.0
     e    6.0
dtype: float64